# docker-compose.yml
version: "3"
services:
  fastify-api:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
    ports:
      - "8000:8000"
      - "9229:9229"
    command: npm run dev
    volumes:
      - ./src:/usr/src/app/src

  postgres:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
