const textStyles = {
  // Headings will be removed once finished changing the whole text for the app
  heading: {
    h1: {
      fontFamily: `"Jost", "Inter"`,
      fontStyle: "normal",
      fontWeight: "normal",
      fontSize: "1.5rem",
      lineHeight: "2rem",
      color: "#542C0D",
    },
    h2: {
      fontFamily: `"Jost", "Inter"`,
      fontStyle: "normal",
      fontWeight: "normal",
      fontSize: "1.25rem",
      lineHeight: "1.5rem",
      color: "#542C0D",
    },
    h3: {
      fontFamily: `"Jost", "Inter"`,
      fontStyle: "normal",
      fontWeight: "normal",
      fontSize: "1rem",
      lineHeight: "1.125rem",
      color: "#542C0D",
    },
  },
  action: {
    fontFamily: `"Inter", "Lato"`,
    fontStyle: "normal",
    fontWeight: "500",
    fontSize: "1rem",
    lineHeight: "1.25rem",
    color: "#542C0D",
  },
  categories: {
    fontFamily: `"Lato", "Inter"`,
    fontStyle: "normal",
    fontWeight: "700",
    fontSize: "1.375rem",
    lineHeight: "1.25rem",
    color: "#542C0D",
  },
  body: {
    fontFamily: `"Inter", "Lato"`,
    fontStyle: "normal",
    fontWeight: "normal",
    fontSize: "0.875rem",
    lineHeight: "1.125rem",
    color: "#542C0D",
  },
  fieldLabel: {
    fontFamily: `"Inter", "Lato"`,
    fontStyle: "normal",
    fontWeight: "500",
    fontSize: "0.875rem",
    lineHeight: "1.125rem",
    color: "#542C0D",
  },
  fieldInput: {
    fontFamily: `"Inter", "Lato"`,
    fontStyle: "normal",
    fontWeight: "normal",
    fontSize: "1rem",
    lineHeight: "1.375rem",
    color: "#542C0D",
  },
  detailText: {
    fontFamily: `"Inter", "Lato"`,
    fontStyle: "normal",
    fontWeight: "normal",
    fontSize: "0.625rem",
    lineHeight: "1rem",
    color: "#542C0D",
  },
  error: {
    fontFamily: `"Inter", "Lato"`,
    fontStyle: "italic",
    fontWeight: "normal",
    fontSize: "0.75rem",
    lineHeight: "1.125rem",
    color: "hsla(17, 99%, 48%, 1)",
  },
  quote: {
    fontFamily: `"Inter", "Lato"`,
    fontStyle: "italic",
    fontWeight: "300",
    fontSize: "1rem",
    lineHeight: "1.5rem",
    color: "#542C0D",
  },
};

export default textStyles;
