# docker-compose.yml
version: "3"
services:
  vite-web:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - "5173:5173"
    command: npm run dev
    volumes:
      - ./src:/usr/src/app/src
